services:
  _defaults:
    autoconfigure: true
    public: true

  inspiredminds.fieldsetduplication.listener.formhook:
    class: InspiredMinds\ContaoFieldsetDuplication\EventListener\FormHookListener
    arguments:
      - '@request_stack'
      - '@inspiredminds.fieldsetduplication.helper.field'
    tags:
      - { name: contao.hook, hook: loadFormField, method: onLoadFormField }
      - { name: contao.hook, hook: compileFormFields, method: onCompileFormFields, priority: -100}
      - { name: contao.hook, hook: storeFormData, method: onStoreFormData, priority: 100 }
      - { name: contao.hook, hook: prepareFormData, method: onPrepareFormData }

  InspiredMinds\ContaoFieldsetDuplication\EventListener\FormFieldDcaListener:
    arguments:
      - '@inspiredminds.fieldsetduplication.helper.field'

  InspiredMinds\ContaoFieldsetDuplication\EventListener\LeadsListener:
    autowire: true
    bind:
      $fieldHelper: '@inspiredminds.fieldsetduplication.helper.field'

  inspiredminds.fieldsetduplication.helper.field:
    class: InspiredMinds\ContaoFieldsetDuplication\Helper\FieldHelper

  inspiredminds.fieldsetduplication.migration.notificationtokentemplates:
    class: InspiredMinds\ContaoFieldsetDuplication\Migration\NotificationTokenTemplatesMigration
    arguments:
      - '@database_connection'
