services:
  _defaults:
    autoconfigure: true
    public: true

  inspiredminds.fieldsetduplication.listener.formhook:
    class: InspiredMinds\ContaoFieldsetDuplication\EventListener\FormHookListener
    arguments:
      - '@request_stack'
      - '@inspiredminds.fieldsetduplication.helper.field'

  InspiredMinds\ContaoFieldsetDuplication\EventListener\FormFieldDcaListener:
    arguments:
      - '@inspiredminds.fieldsetduplication.helper.field'

  InspiredMinds\ContaoFieldsetDuplication\EventListener\LeadsListener:
    arguments:
      - '@database_connection'
      - '@inspiredminds.fieldsetduplication.helper.field'

  inspiredminds.fieldsetduplication.helper.field:
    class: InspiredMinds\ContaoFieldsetDuplication\Helper\FieldHelper

  inspiredminds.fieldsetduplication.migration.notificationtokentemplates:
    class: InspiredMinds\ContaoFieldsetDuplication\Migration\NotificationTokenTemplatesMigration
    arguments:
      - '@database_connection'
